baseurl: "https://example.com"
languageCode: "en-us"
title: "ro"
theme: "hugo-tania"
paginate: 6

params:
  # Emoji will show before the blog title on site navbar.
  titleEmoji: 

  # Logo will show before the blog title on site navbar.
  titleLogo: lauro.ico
  
  # Enable float footnotes.
  # Default to true
  enableFootnotes: true
  siteName: "agitated-kalam"
  siteDesc: "Blog sobre data science"
  author: "Rodrigo Amaro"


  # Limit how many categories filter show above search input.
  # Default to 5
  maxCategoryToShow: 10

  # Show your socail information with icon on index bio with `_index.md` content.
  socialOptions:
    dev-to:
    email: 
    facebook:
    github:
    instagram:
    linkedin: https://www.linkedin.com/in/roamarox/
    medium:
    stack-overflow:
    steam:
    telegram:
    twitter:
    twitch:
    whatsapp: +5989265868

menu:
  header:
    - name: Articulos
      url: "/articles/"
  

markup:
  highlight:
    noClasses: false
    lineNos: true
  goldmark:
    renderer:
      unsafe: true

outputs:
  home: ["HTML", "RSS", "JSON"]
